<?php

namespace VintageWest\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsRepository extends EntityRepository
{
}
