<?php

namespace VintageWest\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImgCarrouselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgCarrouselRepository extends EntityRepository
{
}
